name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Patch URL
        if: github.event_name == 'pull_request'
        run: |
          sed -i "s#baseUrl: '/'#baseUrl: '/pr-${{ github.event.number }}/'#" docusaurus.config.js
          cat docusaurus.config.js | grep baseUrl

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install yarn
        run: sudo npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Fix audit
        run: npm_config_yes=true npx yarn-audit-fix

      - name: Build master docs
        if: github.event_name == 'push'
        run: yarn build

      - name: Build PR docs
        if: github.event_name == 'pull_request'
        run: yarn build --out-dir=build/pr-${{ github.event.number }}

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
            path: build

      - name: Deploy
        if: github.actor != 'dependabot[bot]'
        id: deployment
        uses: actions/deploy-pages@v2
